// -------------------------------------------------------------------------------					
//  Value Set. File: 					eHDSIUnit.fsh
// -------------------------------------------------------------------------------					
ValueSet: EHDSIUnit					
Id: eHDSIUnit					
Title: "eHDSI Unit"					
Description: """eHDSI Unit"""					
// * url = "http://terminology.hl7.it/ConceptMap/ConceptMap-subject2osiris"					
// * ^status = #active					
* ^experimental = false
* ^version = "8.0.1"

// * insert LOINCCopyrightForVS
* insert SetFmmandStatusRule ( 1, draft )
* insert setOID ( 1.3.6.1.4.1.12559.11.10.1.3.1.42.16 )
* insert setUrl ( eHDSIUnit )
					
* $ucum#1  "Unit"
* $ucum#%  "percent"
* $ucum#%{abnormal}  "percent abnormal"
* $ucum#%{activity}  "percent activity"
* $ucum#%{aggregation}  "percent aggregation"
* $ucum#%{at_60_min}  "percent at 60 minute"
* $ucum#%{bacteria}  "percent of bacteria"
* $ucum#%{basal_activity}  "percent basal activity"
* $ucum#%{baseline}  "percent of baseline"
* $ucum#%{binding}  "percent binding"
* $ucum#%{blockade}  "percent blockade"
* $ucum#%{blocked}  "percent blocked"
* $ucum#%{bound}  "percent bound"
* $ucum#%{breakdown}  "percent breakdown"
* $ucum#%{cells}  "percent of cells"
* $ucum#%{deficient}  "percent deficient"
* $ucum#%{dose}  "percent dose"
* $ucum#%{excretion}  "percent excretion"
* $ucum#%{Hb}  "percent hemoglobin"
* $ucum#%{hemolysis}  "percent hemolysis"
* $ucum#%{index}  "percent index"
* $ucum#%{inhibition}  "percent inhibition"
* $ucum#%{loss_AChR}  "percent loss of acetylcholine receptor"
* $ucum#%{loss}  "percent loss"
* $ucum#%{lysis}  "percent lysis"
* $ucum#%{normal}  "percent normal"
* $ucum#%{penetration}  "percent penetration"
* $ucum#%{pooled_plasma}  "percent normal pooled plasma"
* $ucum#%{positive}  "percent positive"
* $ucum#%{RBCs}  "percent of red blood cells"
* $ucum#%{reactive}  "percent reactive"
* $ucum#%{recovery}  "percent recovery"
* $ucum#%{reference}  "percent reference"
* $ucum#%{relative}  "relative percent"
* $ucum#%{residual}  "percent residual"
* $ucum#%{response}  "percent response"
* $ucum#%{saturation}  "percent saturation"
* $ucum#%{total}  "percent total"
* $ucum#%{uptake}  "percent uptake"
* $ucum#%{viable}  "percent viable"
* $ucum#%{vol}  "percent by volume"
* $ucum#%{WBCs}  "percent of white blood cells"
* $ucum#/(12.h)  "per twelve hour"
* $ucum#/[arb'U]  "per arbitrary unit"
* $ucum#/[HPF]  "per high power field"
* $ucum#/[IU]  "per international unit"
* $ucum#/[LPF]  "per low power field"
* $ucum#/{entity}  "per entity"
* $ucum#/{OIF}  "per oil immersion field"
* $ucum#/10*10  "per 10 billion"
* $ucum#/10*12  "per trillion"
* $ucum#/10*12{RBCs}  "per trillion red blood cells"
* $ucum#/10*3  "per thousand"
* $ucum#/10*3{RBCs}  "per thousand red blood cells"
* $ucum#/10*4{RBCs}  "per 10 thousand red blood cells"
* $ucum#/10*6  "per million"
* $ucum#/10*9  "per billion"
* $ucum#/100  "per 100"
* $ucum#/100{cells}  "per 100 cells"
* $ucum#/100{neutrophils}  "per 100 neutrophils"
* $ucum#/100{spermatozoa}  "per 100 spermatozoa"
* $ucum#/100{WBCs}  "per 100 white blood cells"
* $ucum#/a  "per year"
* $ucum#/cm[H2O]  "per centimeter of water"
* $ucum#/d  "per day"
* $ucum#/dL  "per deciliter"
* $ucum#/g  "per gram"
* $ucum#/g{creat}  "per gram of creatinine"
* $ucum#/g{Hb}  "per gram of hemoglobin"
* $ucum#/g{tot_nit}  "per gram of total nitrogen"
* $ucum#/g{tot_prot}  "per gram of total protein"
* $ucum#/g{wet_tis}  "per gram of wet tissue"
* $ucum#/h  "per hour"
* $ucum#/kg  "per kilogram"
* $ucum#/kg{body_wt}  "per kilogram of body weight"
* $ucum#/L  "per liter"
* $ucum#/m2  "per square meter"
* $ucum#/m3  "per cubic meter"
* $ucum#/mg  "per milligram"
* $ucum#/min  "per minute"
* $ucum#/mL  "per milliliter"
* $ucum#/mm  "per millimeter"
* $ucum#/mmol{creat}  "per millimole of creatinine"
* $ucum#/mo  "per month"
* $ucum#/s  "per second"
* $ucum#/U  "per enzyme unit"
* $ucum#/uL  "per microliter"
* $ucum#/wk  "per week"
* $ucum#[APL'U]  "IgA anticardiolipin unit**"
* $ucum#[APL'U]/mL  "IgA anticardiolipin unit per milliliter**"
* $ucum#[arb'U]  "arbitrary unit"
* $ucum#[arb'U]/mL  "arbitrary unit per milliliter"
* $ucum#[AU]  "allergy unit"
* $ucum#[bdsk'U]  "Bodansky unit"
* $ucum#[beth'U]  "Bethesda unit"
* $ucum#[CFU]  "colony forming unit"
* $ucum#[CFU]/L  "colony forming unit per liter"
* $ucum#[CFU]/mL  "colony forming unit per milliliter"
* $ucum#[Ch]  "French (catheter gauge)"
* $ucum#[cin_i]  "cubic inch (international)"
* $ucum#[degF]  "degree Fahrenheit"
* $ucum#[diop]  "diopter"
* $ucum#[dr_av]  "dram (US and British)"
* $ucum#[drp]  "drop (1/12 milliliter)"
* $ucum#[foz_us]  "fluid ounce (US)"
* $ucum#[ft_i]  "foot (international)"
* $ucum#[ft_us]/[ft_us]  "feet (US) per feet (US)"
* $ucum#[gal_us]  "gallon (US)"
* $ucum#[GPL'U]  "IgG anticardiolipin unit**"
* $ucum#[GPL'U]/mL  "IgG anticardiolipin unit per milliliter**"
* $ucum#[HPF]  "high power field"
* $ucum#[in_i]  "inch (international)"
* $ucum#[in_i'H2O]  "inch (international) of water"
* $ucum#[in_us]  "inches (US)"
* $ucum#[IU]  "international unit"
* $ucum#[IU]/(2.h)  "international unit per 2 hour"
* $ucum#[IU]/(24.h)  "international unit per 24 hour"
* $ucum#[IU]/10*9{RBCs}  "international unit per billion red blood cells"
* $ucum#[IU]/d  "international unit per day"
* $ucum#[IU]/dL  "international unit per deciliter"
* $ucum#[IU]/g  "international unit per gram"
* $ucum#[IU]/g{Hb}  "international unit per gram of hemoglobin"
* $ucum#[IU]/h  "international unit per hour"
* $ucum#[IU]/kg  "international unit per kilogram"
* $ucum#[IU]/kg/d  "international unit per kilogram per day"
* $ucum#[IU]/L  "international unit per liter"
* $ucum#[IU]/L{37Cel}  "international unit per liter at 37 degrees Celsius"
* $ucum#[IU]/mg{creat}  "international unit per milligram of creatinine"
* $ucum#[IU]/min  "international unit per minute"
* $ucum#[IU]/mL  "international unit per milliliter"
* $ucum#[ka'U]  "King Armstrong unit"
* $ucum#[knk'U]  "Kunkel unit"
* $ucum#[lb_av]  "pound (US and British)"
* $ucum#[LPF]  "low power field"
* $ucum#[mclg'U]  "Maclagan unit"
* $ucum#[MET].min/wk  "metabolic equivalent minute per week"
* $ucum#[mi_i]  "mile (international)"
* $ucum#[MPL'U]  "IgM anticardiolipin unit**"
* $ucum#[MPL'U]/mL  "IgM anticardiolipin unit per milliliter**"
* $ucum#[oz_av]  "ounce (US and British)"
* $ucum#[oz_tr]  "Troy ounce"
* $ucum#[pH]  "pH"
* $ucum#[ppb]  "part per billion"
* $ucum#[ppm]  "part per million"
* $ucum#[ppm]{v/v}  "part per million in volume per volume"
* $ucum#[ppth]  "part per thousand"
* $ucum#[pptr]  "part per trillion"
* $ucum#[psi]  "pound per square inch"
* $ucum#[pt_us]  "pint (US)"
* $ucum#[qt_us]  "quart (US)"
* $ucum#[sft_i]  "square foot (international)"
* $ucum#[sin_i]  "square inch (international)"
* $ucum#[syd_i]  "square yard (international)"
* $ucum#[tbs_us]  "tablespoon (US)"
* $ucum#[tb'U]  "tuberculin unit"
* $ucum#[todd'U]  "Todd unit"
* $ucum#[tsp_us]  "teaspoon (US)"
* $ucum#[yd_i]  "yard (international)"
* $ucum#{#}  "number"
* $ucum#{#}/[HPF]  "number per high power field"
* $ucum#{#}/[LPF]  "number per low power field"
* $ucum#{#}/{platelet}  "molecule per platelet"
* $ucum#{#}/a  "number per annum (year)"
* $ucum#{#}/d  "number per day"
* $ucum#{#}/g  "number per gram"
* $ucum#{#}/L  "number per liter"
* $ucum#{#}/min  "number per minute"
* $ucum#{#}/mL  "number per milliliter"
* $ucum#{#}/uL  "number per microliter"
* $ucum#{#}/wk  "number per week"
* $ucum#{absorbance}  "absorbance"
* $ucum#{activity}  "activity"
* $ucum#{AHF'U}  "American Hospital Formulary unit"
* $ucum#{APS'U}  "IgA antiphosphatidylserine unit"
* $ucum#{ARU}  "aspirin response unit"
* $ucum#{beats}/min  "heart beats per minute"
* $ucum#{binding_index}  "binding index"
* $ucum#{breaths}/min  "breaths per minute"
* $ucum#{CAE'U}  "complement activity enzyme unit"
* $ucum#{CAG_repeats}  "CAG trinucleotide repeats"
* $ucum#{cells}  "cells"
* $ucum#{cells}/[HPF]  "cells per high power field"
* $ucum#{cells}/uL  "cells per microliter"
* $ucum#{CH100'U}  "complement CH100 unit"
* $ucum#{clock_time}  "clock time e.g 12:30PM"
* $ucum#{copies}  "copies"
* $ucum#{copies}/mL  "copies per milliliter"
* $ucum#{copies}/ug  "copies per microgram"
* $ucum#{count}  "count"
* $ucum#{CPM}  "counts per minute"
* $ucum#{CPM}/10*3{cell}  "counts per minute per thousand cells"
* $ucum#{Ct_value}  "Cycle threshold value"
* $ucum#{delta_OD}  "change in (delta) optical density"
* $ucum#{dilution}  "dilution"
* $ucum#{Ehrlich'U}  "Ehrlich unit"
* $ucum#{Ehrlich'U}/(2.h)  "Ehrlich unit per 2 hour"
* $ucum#{Ehrlich'U}/100.g  "Ehrlich unit per 100 gram"
* $ucum#{Ehrlich'U}/d  "Ehrlich unit per day"
* $ucum#{Ehrlich'U}/dL  "Ehrlich unit per deciliter"
* $ucum#{EIA_index}  "EIA index"
* $ucum#{EIA_titer}  "EIA titer"
* $ucum#{EIA'U}  "EIA unit"
* $ucum#{EIA'U}/U  "EIA unit per enzyme unit"
* $ucum#{ELISA'U}  "ELISA unit"
* $ucum#{EV}  "EIA value"
* $ucum#{FIU}  "fluorescent intensity unit"
* $ucum#{fraction}  "fraction"
* $ucum#{GAA_repeats}  "GAA trinucleotide repeats"
* $ucum#{genomes}/mL  "genomes per milliliter"
* $ucum#{Globules}/[HPF]  "globules (drops) per high power field"
* $ucum#{GPS'U}  "IgG antiphosphatidylserine unit"
* $ucum#{HA_titer}  "influenza hemagglutination titer"
* $ucum#{IFA_index}  "immunofluorescence assay index"
* $ucum#{IFA_titer}  "Immunofluorescence assay titer"
* $ucum#{ImmuneComplex'U}  "immune complex unit"
* $ucum#{index_val}  "index value"
* $ucum#{index}  "index value"
* $ucum#{INR}  "international normalized ratio"
* $ucum#{ISR}  "immune status ratio"
* $ucum#{JDF'U}  "Juvenile Diabetes Foundation unit"
* $ucum#{JDF'U}/L  "Juvenile Diabetes Foundation unit per liter"
* $ucum#{KCT'U}  "kaolin clotting time"
* $ucum#{KRONU'U}/mL  "Kronus unit per milliliter"
* $ucum#{Log_copies}/mL  "log (base 10) copies per milliliter"
* $ucum#{Log_IU}  "log (base 10) international unit"
* $ucum#{Log_IU}/mL  "log (base 10) international unit per milliliter"
* $ucum#{Log}  "log base 10"
* $ucum#{Lyme_index_value}  "Lyme index value"
* $ucum#{M.o.M}  "multiple of the median"
* $ucum#{minidrop}/min  "minidrop per minute"
* $ucum#{minidrop}/s  "minidrop per second"
* $ucum#{mm/dd/yyyy}  "month-day-year"
* $ucum#{MPS'U}  "IgM antiphosphatidylserine unit"
* $ucum#{MPS'U}/mL  "IgM antiphosphatidylserine unit per milliliter"
* $ucum#{mutation}  "mutation"
* $ucum#{OD_unit}  "optical density unit"
* $ucum#{Pan_Bio'U}  "panbio unit"
* $ucum#{percentile}  "percentile"
* $ucum#{phenotype}  "phenotype"
* $ucum#{ratio}  "ratio"
* $ucum#{RBC}/uL  "red blood cell per microliter"
* $ucum#{rel_saturation}  "relative saturation"
* $ucum#{risk}  "risk"
* $ucum#{Rubella_virus}  "rubella virus"
* $ucum#{s_co_ratio}  "signal to cutoff ratio"
* $ucum#{saturation}  "saturation"
* $ucum#{score}  "score"
* $ucum#{shift}  "shift"
* $ucum#{spermatozoa}/mL  "spermatozoa per milliliter"
* $ucum#{STDV}  "standard deviation"
* $ucum#{titer}  "titer"
* $ucum#{TmStp}  "time stamp"
* $ucum#{Tscore}  "t score"
* $ucum#{TSI_index}  "thyroid-stimulating immunoglobulin index"
* $ucum#{WBCs}  "white blood cells"
* $ucum#{yyyy}  "year"
* $ucum#{Zscore}  "z score"
* $ucum#10*12/L  "trillion per liter"
* $ucum#10*3  "thousand"
* $ucum#10*3/L  "thousand per liter"
* $ucum#10*3/mL  "thousand per milliliter"
* $ucum#10*3/uL  "thousand per microliter"
* $ucum#10*3{copies}/mL  "thousand copies per milliliter"
* $ucum#10*3{RBCs}  "thousand red blood cells"
* $ucum#10*4/uL  "10 thousand per microliter"
* $ucum#10*5  "one hundred thousand"
* $ucum#10*6  "million"
* $ucum#10*6.[CFU]/L  "million colony forming unit per liter"
* $ucum#10*6.[IU]  "million international unit"
* $ucum#10*6/(24.h)  "million per 24 hour"
* $ucum#10*6/kg  "million per kilogram"
* $ucum#10*6/L  "million per liter"
* $ucum#10*6/mL  "million per milliliter"
* $ucum#10*6/uL  "million per microliter"
* $ucum#10*8  "100 million"
* $ucum#10*9/L  "billion per liter"
* $ucum#10*9/mL  "billion per milliliter"
* $ucum#10*9/uL  "billion per microliter"
* $ucum#10.L/(min.m2)  "10 liter per minute per square meter"
* $ucum#10.L/min  "10 liter per minute"
* $ucum#10.uN.s/(cm5.m2)  "10 micronewton second per centimeter to the fifth power per square meter"
* $ucum#24.h  "24 hour"
* $ucum#A  "ampere"
* $ucum#a  "year"
* $ucum#A/m  "ampere per meter"
* $ucum#ag/{cell}  "attogram per cell"
* $ucum#atm  "atmosphere"
* $ucum#bar  "bar"
* $ucum#Bq  "Becquerel"
* $ucum#cal  "calorie"
* $ucum#Cel  "degree Celsius"
* $ucum#cg  "centigram"
* $ucum#cL  "centiliter"
* $ucum#cm  "centimeter"
* $ucum#cm/s  "centimeter per second"
* $ucum#cm[H2O]  "centimeter of water"
* $ucum#cm[H2O]/L/s  "centimeter of water per liter per second"
* $ucum#cm[H2O]/s/m  "centimeter of water per second per meter"
* $ucum#cm[Hg]  "centimeter of mercury"
* $ucum#cm2  "square centimeter"
* $ucum#cm2/s  "square centimeter per second"
* $ucum#cm3  "cubic centimeter"
* $ucum#cP  "centipoise"
* $ucum#cSt  "centistoke"
* $ucum#d  "day"
* $ucum#d/(7.d)  "day per 7 day"
* $ucum#d/wk  "days per week"
* $ucum#daL/min  "dekaliter per minute"
* $ucum#daL/min/m2  "dekaliter per minute per square meter"
* $ucum#dB  "decibel"
* $ucum#deg  "degree (plane angle)"
* $ucum#deg/s  "degree per second"
* $ucum#dg  "decigram"
* $ucum#dL  "deciliter"
* $ucum#dm  "decimeter"
* $ucum#dm2/s2  "square decimeter per square second"
* $ucum#dyn.s/(cm.m2)  "dyne second per centimeter per square meter"
* $ucum#dyn.s/cm  "dyne second per centimeter"
* $ucum#eq  "equivalent"
* $ucum#eq/L  "equivalent per liter"
* $ucum#eq/mL  "equivalent per milliliter"
* $ucum#eq/mmol  "equivalent per millimole"
* $ucum#eq/umol  "equivalent per micromole"
* $ucum#erg  "erg"
* $ucum#eV  "electron Volt"
* $ucum#F  "Farad"
* $ucum#fg  "femtogram"
* $ucum#fL  "femtoliter"
* $ucum#fm  "femtometer"
* $ucum#fmol  "femtomole"
* $ucum#fmol/g  "femtomole per gram"
* $ucum#fmol/L  "femtomole per liter"
* $ucum#fmol/mg  "femtomole per milligram"
* $ucum#fmol/mg{cyt_prot}  "femtomole per milligram of cytosol protein"
* $ucum#fmol/mg{prot}  "femtomole per milligram of protein"
* $ucum#fmol/mL  "femtomole per milliliter"
* $ucum#g  "gram"
* $ucum#g.m  "gram meter"
* $ucum#g.m/{beat}  "gram meter per heart beat"
* $ucum#g/(100.g)  "gram per 100 gram"
* $ucum#g/(12.h)  "gram per 12 hour"
* $ucum#g/(24.h)  "gram per 24 hour"
* $ucum#g/(3.d)  "gram per 3 days"
* $ucum#g/(4.h)  "gram per 4 hour"
* $ucum#g/(48.h)  "gram per 48 hour"
* $ucum#g/(5.h)  "gram per 5 hour"
* $ucum#g/(6.h)  "gram per 6 hour"
* $ucum#g/(72.h)  "gram per 72 hour"
* $ucum#g/(8.h){shift}  "gram per 8 hour shift"
* $ucum#g/{specimen}  "gram per specimen"
* $ucum#g/{total_output}  "gram per total output"
* $ucum#g/{total_weight}  "gram per total weight"
* $ucum#g/cm2  "gram per square centimeter"
* $ucum#g/cm3  "gram per cubic centimeter"
* $ucum#g/d  "gram per day"
* $ucum#g/dL  "gram per deciliter"
* $ucum#g/g  "gram per gram"
* $ucum#g/g{creat}  "gram per gram of creatinine"
* $ucum#g/g{globulin}  "gram per gram of globulin"
* $ucum#g/g{tissue}  "gram per gram of tissue"
* $ucum#g/h  "gram per hour"
* $ucum#g/h/m2  "gram per hour per square meter"
* $ucum#g/kg  "gram per kilogram"
* $ucum#g/kg/(8.h)  "gram per kilogram per 8 hour"
* $ucum#g/kg/(8.h){shift}  "gram per kilogram per 8 hour shift"
* $ucum#g/kg/d  "gram per kilogram per day"
* $ucum#g/kg/h  "gram per kilogram per hour"
* $ucum#g/kg/min  "gram per kilogram per minute"
* $ucum#g/L  "gram per liter"
* $ucum#g/m2  "gram per square meter"
* $ucum#g/mg  "gram per milligram"
* $ucum#g/min  "gram per minute"
* $ucum#g/mL  "gram per milliliter"
* $ucum#g/mmol  "gram per millimole"
* $ucum#g/mol{creat}  "gram per mole of creatinine"
* $ucum#g{creat}  "gram of creatinine"
* $ucum#g{Hb}  "gram of hemoglobin"
* $ucum#g{total_nit}  "gram of total nitrogen"
* $ucum#g{total_prot}  "gram of total protein"
* $ucum#g{wet_tissue}  "gram of wet tissue"
* $ucum#Gy  "Gray"
* $ucum#H  "Henry"
* $ucum#h  "hour"
* $ucum#h/d  "hour per day"
* $ucum#h/wk  "hour per week"
* $ucum#Hz  "Hertz"
* $ucum#J  "joule"
* $ucum#J/L  "joule per liter"
* $ucum#K  "degree Kelvin"
* $ucum#K/W  "degree Kelvin per Watt"
* $ucum#k[IU]/L  "kilo international unit per liter"
* $ucum#k[IU]/mL  "kilo international unit per milliliter"
* $ucum#kat  "katal"
* $ucum#kat/kg  "katal per kilogram"
* $ucum#kat/L  "katal per liter"
* $ucum#kcal  "kilocalorie"
* $ucum#kcal/(24.h)  "kilocalorie per 24 hour"
* $ucum#kcal/[oz_av]  "kilocalorie per ounce (US & British)"
* $ucum#kcal/d  "kilocalorie per day"
* $ucum#kcal/h  "kilocalorie per hour"
* $ucum#kcal/kg/(24.h)  "kilocalorie per kilogram per 24 hour"
* $ucum#kg  "kilogram"
* $ucum#kg.m/s  "kilogram meter per second"
* $ucum#kg/(s.m2)  "kilogram per second per square meter"
* $ucum#kg/h  "kilogram per hour"
* $ucum#kg/L  "kilogram per liter"
* $ucum#kg/m2  "kilogram per square meter"
* $ucum#kg/m3  "kilogram per cubic meter"
* $ucum#kg/min  "kilogram per minute"
* $ucum#kg/mol  "kilogram per mole"
* $ucum#kg/s  "kilogram per second"
* $ucum#kL  "kiloliter"
* $ucum#km  "kilometer"
* $ucum#kPa  "kilopascal"
* $ucum#ks  "kilosecond"
* $ucum#kU  "kilo enzyme unit"
* $ucum#kU/g  "kilo enzyme unit per gram"
* $ucum#kU/L  "kilo enzyme unit per liter"
* $ucum#kU/L{class}  "kilo enzyme unit per liter class"
* $ucum#kU/mL  "kilo enzyme unit per milliliter"
* $ucum#L  "liter"
* $ucum#L/(24.h)  "liter per 24 hour"
* $ucum#L/(8.h)  "liter per 8 hour"
* $ucum#L/(min.m2)  "liter per minute per square meter"
* $ucum#L/d  "liter per day"
* $ucum#L/h  "liter per hour"
* $ucum#L/kg  "liter per kilogram"
* $ucum#L/L  "liter per liter"
* $ucum#L/min  "liter per minute"
* $ucum#L/min/m2  "liter per minute per sqaure meter"
* $ucum#L/s  "liter per second"
* $ucum#L/s/s2  "liter per second per square second"
* $ucum#lm  "lumen"
* $ucum#lm.m2  "lumen square meter"
* $ucum#m  "meter"
* $ucum#m/s  "meter per second"
* $ucum#m/s2  "meter per square second"
* $ucum#m[IU]/L  "milli international unit per liter"
* $ucum#m[IU]/mL  "milli international unit per milliliter"
* $ucum#m2  "square meter"
* $ucum#m2/s  "square meter per second"
* $ucum#m3/s  "cubic meter per second"
* $ucum#mA  "milliampere"
* $ucum#mbar  "millibar"
* $ucum#mbar.s/L  "millibar second per liter"
* $ucum#mbar/L/s  "millibar per liter per second"
* $ucum#meq  "milliequivalent"
* $ucum#meq/(2.h)  "milliequivalent per 2 hour"
* $ucum#meq/(24.h)  "milliequivalent per 24 hour"
* $ucum#meq/(8.h)  "milliequivalent per 8 hour"
* $ucum#meq/{specimen}  "milliequivalent per specimen"
* $ucum#meq/{total_volume}  "milliequivalent per total volume"
* $ucum#meq/d  "milliequivalent per day"
* $ucum#meq/dL  "milliequivalent per deciliter"
* $ucum#meq/g  "milliequivalent per gram"
* $ucum#meq/g{creat}  "milliequivalent per gram of creatinine"
* $ucum#meq/h  "milliequivalent per hour"
* $ucum#meq/kg  "milliequivalent per kilogram"
* $ucum#meq/kg/h  "milliequivalent per kilogram per hour"
* $ucum#meq/L  "milliequivalent per liter"
* $ucum#meq/m2  "milliequivalent per square meter"
* $ucum#meq/min  "milliequivalent per minute"
* $ucum#meq/mL  "milliequivalent per milliliter"
* $ucum#mg  "milligram"
* $ucum#mg/(10.h)  "milligram per 10 hour"
* $ucum#mg/(12.h)  "milligram per 12 hour"
* $ucum#mg/(2.h)  "milligram per 2 hour"
* $ucum#mg/(24.h)  "milligram per 24 hour"
* $ucum#mg/(6.h)  "milligram per 6 hour"
* $ucum#mg/(72.h)  "milligram per 72 hour"
* $ucum#mg/(8.h)  "milligram per 8 hour"
* $ucum#mg/{collection}  "milligram per collection"
* $ucum#mg/{specimen}  "milligram per specimen"
* $ucum#mg/{total_output}  "milligram per total output"
* $ucum#mg/{total_volume}  "milligram per total volume"
* $ucum#mg/d  "milligram per day"
* $ucum#mg/d/{1.73_m2}  "milligram per day per 1.73 square meter"
* $ucum#mg/dL  "milligram per deciliter"
* $ucum#mg/dL{RBCs}  "milligram per deciliter of red blood cells"
* $ucum#mg/g  "milligram per gram"
* $ucum#mg/g{creat}  "milligram per gram of creatinine"
* $ucum#mg/g{dry_tissue}  "milligram per gram of dry tissue"
* $ucum#mg/g{feces}  "milligram per gram of feces"
* $ucum#mg/g{tissue}  "milligram per gram of tissue"
* $ucum#mg/g{wet_tissue}  "milligram per gram of wet tissue"
* $ucum#mg/h  "milligram per hour"
* $ucum#mg/kg  "milligram per kilogram"
* $ucum#mg/kg/(8.h)  "milligram per kilogram per 8 hour"
* $ucum#mg/kg/d  "milligram per kilogram per day"
* $ucum#mg/kg/h  "milligram per kilogram per hour"
* $ucum#mg/kg/min  "milligram per kilogram per minute"
* $ucum#mg/L  "milligram per liter"
* $ucum#mg/L{RBCs}  "milligram per liter of red blood cells"
* $ucum#mg/m2  "milligram per square meter"
* $ucum#mg/m3  "milligram per cubic meter"
* $ucum#mg/mg  "milligram per milligram"
* $ucum#mg/mg{creat}  "milligram per milligram of creatinine"
* $ucum#mg/min  "milligram per minute"
* $ucum#mg/mL  "milligram per milliliter"
* $ucum#mg/mmol  "milligram per millimole"
* $ucum#mg/mmol{creat}  "milligram per millimole of creatinine"
* $ucum#mg/wk  "milligram per week"
* $ucum#mg{FEU}/L  "milligram fibrinogen equivalent unit per liter"
* $ucum#min  "minute"
* $ucum#min/d  "minute per day"
* $ucum#min/wk  "minute per week"
* $ucum#mL  "milliliter"
* $ucum#mL/(10.h)  "milliliter per 10 hour"
* $ucum#mL/(12.h)  "milliliter per 12 hour"
* $ucum#mL/(2.h)  "milliliter per 2 hour"
* $ucum#mL/(24.h)  "milliliter per 24 hour"
* $ucum#mL/(4.h)  "milliliter per 4 hour"
* $ucum#mL/(5.h)  "milliliter per 5 hour"
* $ucum#mL/(6.h)  "milliliter per 6 hour"
* $ucum#mL/(72.h)  "milliliter per 72 hour"
* $ucum#mL/(8.h)  "milliliter per 8 hour"
* $ucum#mL/(8.h)/kg  "milliliter per 8 hour per kilogram"
* $ucum#mL/[sin_i]  "milliliter per square inch (international)"
* $ucum#mL/{beat}  "milliliter per heart beat"
* $ucum#mL/{beat}/m2  "milliliter per heart beat per square meter"
* $ucum#mL/cm[H2O]  "milliliter per centimeter of water"
* $ucum#mL/d  "milliliter per day"
* $ucum#mL/dL  "milliliter per deciliter"
* $ucum#mL/h  "milliliter per hour"
* $ucum#mL/kg  "milliliter per kilogram"
* $ucum#mL/kg/(8.h)  "milliliter per kilogram per 8 hour"
* $ucum#mL/kg/d  "milliliter per kilogram per day"
* $ucum#mL/kg/h  "milliliter per kilogram per hour"
* $ucum#mL/kg/min  "milliliter per kilogram per minute"
* $ucum#mL/m2  "milliliter per square meter"
* $ucum#mL/mbar  "milliliter per millibar"
* $ucum#mL/min  "milliliter per minute"
* $ucum#mL/min/{1.73_m2}  "milliliter per minute per 1.73 square meter"
* $ucum#mL/min/m2  "milliliter per minute per square meter"
* $ucum#mL/mm  "milliliter per millimeter"
* $ucum#mL/s  "milliliter per second"
* $ucum#mL{fetal_RBCs}  "milliliter of fetal red blood cells"
* $ucum#mm  "millimeter"
* $ucum#mm/h  "millimeter per hour"
* $ucum#mm/min  "millimeter per minute"
* $ucum#mm[H2O]  "millimeter of water"
* $ucum#mm[Hg]  "millimeter of mercury"
* $ucum#mm2  "square millimeter"
* $ucum#mmol  "millimole"
* $ucum#mmol/(12.h)  "millimole per 12 hour"
* $ucum#mmol/(2.h)  "millimole per 2 hour"
* $ucum#mmol/(24.h)  "millimole per 24 hour"
* $ucum#mmol/(5.h)  "millimole per 5 hour"
* $ucum#mmol/(6.h)  "millimole per 6 hour"
* $ucum#mmol/(8.h)  "millimole per 8 hour"
* $ucum#mmol/{ejaculate}  "millimole per ejaculate"
* $ucum#mmol/{specimen}  "millimole per specimen"
* $ucum#mmol/{total_vol}  "millimole per total volume"
* $ucum#mmol/d  "millimole per day"
* $ucum#mmol/dL  "millimole per deciliter"
* $ucum#mmol/g  "millimole per gram"
* $ucum#mmol/g{creat}  "millimole per gram of creatinine"
* $ucum#mmol/h  "millimole per hour"
* $ucum#mmol/h/mg{Hb}  "millimole per hour per milligram of hemoglobin"
* $ucum#mmol/h/mg{prot}  "millimole per hour per milligram of protein"
* $ucum#mmol/kg  "millimole per kilogram"
* $ucum#mmol/kg/(8.h)  "millimole per kilogram per 8 hour"
* $ucum#mmol/kg/d  "millimole per kilogram per day"
* $ucum#mmol/kg/h  "millimole per kilogram per hour"
* $ucum#mmol/kg/min  "millimole per kilogram per minute"
* $ucum#mmol/L  "millimole per liter"
* $ucum#mmol/L{RBCs}  "millimole per liter of red blood cells"
* $ucum#mmol/m2  "millimole per square meter"
* $ucum#mmol/min  "millimole per minute"
* $ucum#mmol/mmol  "millimole per millimole"
* $ucum#mmol/mmol{creat}  "millimole per millmole of creatinine"
* $ucum#mmol/mmol{urea}  "millimole per millimole of urea"
* $ucum#mmol/mol  "millimole per mole"
* $ucum#mmol/mol{creat}  "millimole per mole of creatinine"
* $ucum#mmol/s/L  "millimole per second per liter"
* $ucum#mo  "month"
* $ucum#mol  "mole"
* $ucum#mol/kg  "mole per kilogram"
* $ucum#mol/kg/s  "mole per kilogram per second"
* $ucum#mol/L  "mole per liter"
* $ucum#mol/m3  "mole per cubic meter"
* $ucum#mol/mL  "mole per milliliter"
* $ucum#mol/mol  "mole per mole"
* $ucum#mol/s  "mole per second"
* $ucum#mosm  "milliosmole"
* $ucum#mosm/kg  "milliosmole per kilogram"
* $ucum#mosm/L  "milliosmole per liter"
* $ucum#mPa  "millipascal"
* $ucum#mPa.s  "millipascal second"
* $ucum#Ms  "megasecond"
* $ucum#ms  "millisecond"
* $ucum#mU/g  "milli enzyme unit per gram"
* $ucum#mU/g{Hb}  "milli enzyme unit per gram of hemoglobin"
* $ucum#mU/g{prot}  "milli enzyme unit per gram of protein"
* $ucum#mU/L  "milli enzyme unit per liter"
* $ucum#mU/mg  "milli enzyme unit per milligram"
* $ucum#mU/mg{creat}  "milli enzyme unit per milligram of creatinine"
* $ucum#mU/mL  "milli enzyme unit per milliliter"
* $ucum#mU/mL/min  "milli enzyme unit per milliliter per minute"
* $ucum#mU/mmol{creat}  "milli enzyme unit per millimole of creatinine"
* $ucum#mU/mmol{RBCs}  "milli enzyme unit per millimole of red blood cells"
* $ucum#mV  "millivolt"
* $ucum#mV/s  "millivolt per second"
* $ucum#N  "Newton"
* $ucum#N.cm  "Newton centimeter"
* $ucum#N.s  "Newton second"
* $ucum#ng  "nanogram"
* $ucum#ng/(24.h)  "nanogram per 24 hour"
* $ucum#ng/(8.h)  "nanogram per 8 hour"
* $ucum#ng/10*6  "nanogram per million"
* $ucum#ng/10*6{RBCs}  "nanogram per million red blood cells"
* $ucum#ng/d  "nanogram per day"
* $ucum#ng/dL  "nanogram per deciliter"
* $ucum#ng/g  "nanogram per gram"
* $ucum#ng/g{creat}  "nanogram per gram of creatinine"
* $ucum#ng/h  "nanogram per hour"
* $ucum#ng/kg  "nanogram per kilogram"
* $ucum#ng/kg/(8.h)  "nanogram per kilogram per 8 hour"
* $ucum#ng/kg/h  "nanogram per kilogram per hour"
* $ucum#ng/kg/min  "nanogram per kilogram per minute"
* $ucum#ng/L  "nanogram per liter"
* $ucum#ng/m2  "nanogram per square meter"
* $ucum#ng/mg  "nanogram per milligram"
* $ucum#ng/mg/h  "nanogram per milligram per hour"
* $ucum#ng/mg{creat}  "nanogram per milligram of creatinine"
* $ucum#ng/mg{prot}  "nanogram per milligram of protein"
* $ucum#ng/min  "nanogram per minute"
* $ucum#ng/mL  "nanogram per millliiter"
* $ucum#ng/mL/h  "nanogram per milliliter per hour"
* $ucum#ng/mL{RBCs}  "nanogram per milliliter of red blood cells"
* $ucum#ng/s  "nanogram per second"
* $ucum#ng/U  "nanogram per enzyme unit"
* $ucum#ng{FEU}/mL  "nanogram fibrinogen equivalent unit per milliliter"
* $ucum#nkat  "nanokatal"
* $ucum#nL  "nanoliter"
* $ucum#nm  "nanometer"
* $ucum#nm/s/L  "nanometer per second per liter"
* $ucum#nmol  "nanomole"
* $ucum#nmol/(24.h)  "nanomole per 24 hour"
* $ucum#nmol/d  "nanomole per day"
* $ucum#nmol/dL  "nanomole per deciliter"
* $ucum#nmol/dL{GF}  "nanomole per deciliter of glomerular filtrate"
* $ucum#nmol/g  "nanomole per gram"
* $ucum#nmol/g{creat}  "nanomole per gram of creatinine"
* $ucum#nmol/g{dry_wt}  "nanomole per gram of dry weight"
* $ucum#nmol/h/L  "nanomole per hour per liter"
* $ucum#nmol/h/mg{prot}  "nanomole per hour per milligram of protein"
* $ucum#nmol/h/mL  "nanomole per hour per milliliter"
* $ucum#nmol/L  "nanomole per liter"
* $ucum#nmol/L/mmol{creat}  "nanomole per liter per millimole of creatinine"
* $ucum#nmol/L{RBCs}  "nanomole per liter of red blood cells"
* $ucum#nmol/m/mg{prot}  "nanomole per meter per milligram of protein"
* $ucum#nmol/mg  "nanomole per milligram"
* $ucum#nmol/mg/h  "nanomole per milligram per hour"
* $ucum#nmol/mg{creat}  "nanomole per milligram of creatinine"
* $ucum#nmol/mg{prot}  "nanomole per milligram of protein"
* $ucum#nmol/mg{prot}/h  "nanomole per milligram of protein per hour"
* $ucum#nmol/min  "nanomole per minute"
* $ucum#nmol/min/10*6{cells}  "nanomole per minute per million cells"
* $ucum#nmol/min/mg{Hb}  "nanomole per minute per milligram of hemoglobin"
* $ucum#nmol/min/mg{prot}  "nanomole per minute per milligram of protein"
* $ucum#nmol/min/mg{protein}  "nanomole per minute per milligram protein"
* $ucum#nmol/min/mL  "nanomole per minute per milliliter"
* $ucum#nmol/mL  "nanomole per milliliter"
* $ucum#nmol/mL/h  "nanomole per milliliter per hour"
* $ucum#nmol/mL/min  "nanomole per milliliter per minute"
* $ucum#nmol/mmol  "nanomole per millimole"
* $ucum#nmol/mmol{creat}  "nanomole per millimole of creatinine"
* $ucum#nmol/mol  "nanomole per mole"
* $ucum#nmol/mol{creat}  "nanomole per mole creatinine"
* $ucum#nmol/nmol  "nanomole per nanomole"
* $ucum#nmol/s  "nanomole per second"
* $ucum#nmol/s/L  "nanomole per second per liter"
* $ucum#nmol/umol{creat}  "nanomole per micromole of creatinine"
* $ucum#nmol{ATP}  "nanomole of ATP"
* $ucum#nmol{BCE}  "nanomole bone collagen equivalent"
* $ucum#nmol{BCE}/L  "nanomole bone collagen equivalent per liter"
* $ucum#ns  "nanosecond"
* $ucum#nU/{RBC}  "nanoenzyme unit per red blood cell"
* $ucum#nU/mL  "nanoenzyme unit per milliliter"
* $ucum#Ohm  "Ohm"
* $ucum#Ohm.m  "Ohm meter"
* $ucum#osm  "osmole"
* $ucum#osm/kg  "osmole per kilogram"
* $ucum#osm/L  "osmole per liter"
* $ucum#Pa  "Pascal"
* $ucum#pA  "picoampere"
* $ucum#pg  "picogram"
* $ucum#pg/{cell}  "picogram per cell"
* $ucum#pg/{RBC}  "picogram per red blood cell"
* $ucum#pg/dL  "picogram per deciliter"
* $ucum#pg/L  "picogram per liter"
* $ucum#pg/mg  "picogram per milligram"
* $ucum#pg/mg{creat}  "picogram per milligram of creatinine"
* $ucum#pg/mL  "picogram per milliliter"
* $ucum#pg/mL{sLT}  "picogram per milliliter sulfidoleukotrienes"
* $ucum#pg/mm  "picogram per millimeter"
* $ucum#pkat  "picokatal"
* $ucum#pL  "picoliter"
* $ucum#pm  "picometer"
* $ucum#pmol  "picomole"
* $ucum#pmol/(24.h)  "picomole per 24 hour"
* $ucum#pmol/{RBC}  "picomole per red blood cell"
* $ucum#pmol/d  "picomole per day"
* $ucum#pmol/dL  "picomole per deciliter"
* $ucum#pmol/g  "picomole per gram"
* $ucum#pmol/h/mg{prot}  "picomole per hour per milligram of protein"
* $ucum#pmol/H/mg{protein}  "picomole per hour per milligram protein"
* $ucum#pmol/h/mL  "picomole per hour per milliliter"
* $ucum#pmol/L  "picomole per liter"
* $ucum#pmol/mg{prot}  "picomole per milligram of protein"
* $ucum#pmol/min  "picomole per minute"
* $ucum#pmol/min/mg{prot}  "picomole per minute per milligram of protein"
* $ucum#pmol/mL  "picomole per milliliter"
* $ucum#pmol/mmol{creat}  "picomole per millimole of creatinine"
* $ucum#pmol/umol  "picomole per micromole"
* $ucum#pmol/umol{creat}  "picomole per micromole of creatinine"
* $ucum#ps  "picosecond"
* $ucum#pT  "picotesla"
* $ucum#s  "second"
* $ucum#S  "Siemens"
* $ucum#s/{control}  "second per control"
* $ucum#Sv  "Sievert"
* $ucum#t  "metric ton"
* $ucum#T  "Tesla"
* $ucum#Torr  "Torr"
* $ucum#U  "enzyme unit"
* $ucum#U/(10.g){feces}  "enzyme unit per 10 gram of feces"
* $ucum#U/(12.h)  "enzyme unit per 12 hour"
* $ucum#U/(2.h)  "enzyme unit per 2 hour"
* $ucum#U/(24.h)  "enzyme unit per 24 hour"
* $ucum#U/10  "enzyme unit per 10"
* $ucum#U/10*10  "enzyme unit per 10 billion"
* $ucum#U/10*10{cells}  "enzyme unit per 10 billion cells"
* $ucum#U/10*12  "enzyme unit per trillion"
* $ucum#U/10*12{RBCs}  "enzyme unit per trillion red blood cells"
* $ucum#U/10*6  "enzyme unit per million"
* $ucum#U/10*9  "enzyme unit per billion"
* $ucum#U/d  "enzyme unit per day"
* $ucum#U/dL  "enzyme unit per deciliter"
* $ucum#U/g  "enzyme unit per gram"
* $ucum#U/g{creat}  "enzyme unit per gram of creatinine"
* $ucum#U/g{Hb}  "enzyme unit per gram of hemoglobin"
* $ucum#U/g{protein}  "enzyme unit per gram of protein"
* $ucum#U/h  "enzyme unit per hour"
* $ucum#U/kg{Hb}  "enzyme unit per kilogram of hemoglobin"
* $ucum#U/L  "enzyme unit per liter"
* $ucum#U/min  "enzyme unit per minute"
* $ucum#U/mL  "enzyme unit per milliliter"
* $ucum#U/mL{RBCs}  "enzyme unit per milliliter of red blood cells"
* $ucum#U/mmol{creat}  "enzyme unit per millimole of creatinine"
* $ucum#U/s  "enzyme unit per second"
* $ucum#u[IU]  "micro international unit"
* $ucum#u[IU]/L  "microinternational unit per liter"
* $ucum#u[IU]/mL  "micro international unit per milliliter"
* $ucum#U{25Cel}/L  "enzyme unit per liter at 25 deg Celsius"
* $ucum#U{37Cel}/L  "enzyme unit per liter at 37 deg Celsius"
* $ucum#ueq  "microequivalent"
* $ucum#ueq/L  "microequivalent per liter"
* $ucum#ueq/mL  "microequivalent per milliliter"
* $ucum#ug  "microgram"
* $ucum#ug/(100.g)  "microgram per 100 gram"
* $ucum#ug/(24.h)  "microgram per 24 hour"
* $ucum#ug/(8.h)  "microgram per 8 hour"
* $ucum#ug/[sft_i]  "microgram per square foot (international)"
* $ucum#ug/{specimen}  "microgram per specimen"
* $ucum#ug/d  "microgram per day"
* $ucum#ug/dL  "microgram per deciliter"
* $ucum#ug/dL{RBCs}  "microgram per deciliter of red blood cells"
* $ucum#ug/g  "microgram per gram"
* $ucum#ug/g{creat}  "microgram per gram of creatinine"
* $ucum#ug/g{dry_tissue}  "microgram per gram of dry tissue"
* $ucum#ug/g{dry_wt}  "microgram per gram of dry weight"
* $ucum#ug/g{feces}  "microgram per gram of feces"
* $ucum#ug/g{hair}  "microgram per gram of hair"
* $ucum#ug/g{Hb}  "microgram per gram of hemoglobin"
* $ucum#ug/g{tissue}  "microgram per gram of tissue"
* $ucum#ug/h  "microgram per hour"
* $ucum#ug/kg  "microgram per kilogram"
* $ucum#ug/kg/(8.h)  "microgram per kilogram per 8 hour"
* $ucum#ug/kg/d  "microgram per kilogram per day"
* $ucum#ug/kg/h  "microgram per kilogram per hour"
* $ucum#ug/kg/min  "microgram per kilogram per minute"
* $ucum#ug/L  "microgram per liter"
* $ucum#ug/L/(24.h)  "microgram per liter per 24 hour"
* $ucum#ug/L{RBCs}  "microgram per liter of red blood cells"
* $ucum#ug/m2  "microgram per square meter"
* $ucum#ug/m3  "microgram per cubic meter"
* $ucum#ug/mg  "microgram per milligram"
* $ucum#ug/mg{creat}  "microgram per milligram of creatinine"
* $ucum#ug/min  "microgram per minute"
* $ucum#ug/mL  "microgram per milliliter"
* $ucum#ug/mL{class}  "microgram per milliliter class"
* $ucum#ug/mL{eqv}  "microgram per milliliter equivalent"
* $ucum#ug/mmol  "microgram per millimole"
* $ucum#ug/mmol{creat}  "microgram per millimole of creatinine"
* $ucum#ug/ng  "microgram per nanogram"
* $ucum#ug{FEU}/mL  "microgram fibrinogen equivalent unit per milliliter"
* $ucum#ukat  "microkatal"
* $ucum#uL  "microliter"
* $ucum#uL/(2.h)  "microliter per 2 hour"
* $ucum#uL/h  "microliter per hour"
* $ucum#um  "micrometer"
* $ucum#um/s  "microns per second"
* $ucum#umol  "micromole"
* $ucum#umol/(2.h)  "micromole per 2 hour"
* $ucum#umol/(24.h)  "micromole per 24 hour"
* $ucum#umol/(8.h)  "micromole per 8 hour"
* $ucum#umol/10*6{RBC}  "micromole per million red blood cell"
* $ucum#umol/d  "micromole per day"
* $ucum#umol/dL  "micromole per deciliter"
* $ucum#umol/dL{GF}  "micromole per deciliter of glomerular filtrate"
* $ucum#umol/g  "micromole per gram"
* $ucum#umol/g{creat}  "micromole per gram of creatinine"
* $ucum#umol/g{Hb}  "micromole per gram of hemoglobin"
* $ucum#umol/h  "micromole per hour"
* $ucum#umol/kg  "micromole per kilogram"
* $ucum#umol/kg{feces}  "micromole per kilogram of feces"
* $ucum#umol/L  "micromole per liter"
* $ucum#umol/L/h  "micromole per liter per hour"
* $ucum#umol/L{RBCs}  "micromole per liter of red blood cells"
* $ucum#umol/mg  "micromole per milligram"
* $ucum#umol/mg{creat}  "micromole per milligram of creatinine"
* $ucum#umol/min  "micromole per minute"
* $ucum#umol/min/g  "micromole per minute per gram"
* $ucum#umol/min/g{mucosa}  "micromole per minute per gram of mucosa"
* $ucum#umol/min/g{prot}  "micromole per minute per gram of protein"
* $ucum#umol/min/L  "micromole per minute per liter"
* $ucum#umol/mL  "micromole per milliliter"
* $ucum#umol/mL/min  "micromole per milliliter per minute"
* $ucum#umol/mmol  "micromole per millimole"
* $ucum#umol/mmol{creat}  "micromole per millimole of creatinine"
* $ucum#umol/mol  "micromole per mole"
* $ucum#umol/mol{creat}  "micromole per mole of creatinine"
* $ucum#umol/mol{Hb}  "micromole per mole of hemoglobin"
* $ucum#umol/umol  "micromole per micromole"
* $ucum#umol/umol{creat}  "micromole per micromole of creatinine"
* $ucum#umol{BCE}/mol  "micromole bone collagen equivalent per mole"
* $ucum#uOhm  "microOhm"
* $ucum#us  "microsecond"
* $ucum#uU/g  "micro enzyme unit per gram"
* $ucum#uU/L  "micro enzyme unit per liter"
* $ucum#uU/mL  "micro enzyme unit per milliliter"
* $ucum#uV  "microvolt"
* $ucum#V  "volt"
* $ucum#Wb  "Weber"
* $ucum#wk  "week"
* $ucum#10*-3  "ten to the power of minus three"
* $ucum#10*-3.[IU]/L  "ten to the power of minus three international unit per liter"
* $ucum#10*-6  "ten to the power of minus six"
* $ucum#g/mol  "gram per mole"
* $ucum#mg/mol  "milligram per mole"
* $ucum#nmol/[IU]  "nanomole per international unit"
* $ucum#10*-9  "ten to the power of minus nine"
* $ucum#10*6.[IU]/L  "million international unit per liter"
* $ucum#10*9  "billion"
* $ucum#10*9/kg  "billion per kilogram"
* $ucum#10*3.[arb'U]/L  "million arbitrary unit per liter"
* $ucum#10*3.[IU]/L  "million international unit per liter"
* $ucum#akat  "attokatal"
* $ucum#amol  "attomole"
* $ucum#[arb'U]/L  "arbitrary unit per liter"
* $ucum#cm-2  "per square centimeter"
* $ucum#g/min.m2  "gram per minute square meter"
* $ucum#kBq  "kilobecquerel"
* $ucum#kg/d  "kilogram per day"
* $ucum#kJ/L  "kilojoule per liter"
* $ucum#kU/kg  "kilo enzyme unit per kilogram"
* $ucum#kU/mol  "kilo enzyme unit per mole"
* $ucum#mkat/L  "millikatal per liter"
* $ucum#mkat/mol  "millikatal per mole"
* $ucum#mm2/s  "square millimeter per second"
* $ucum#mmol/m3  "millimole per cubic meter"
* $ucum#mmol/s  "millimole per second"
* $ucum#mol/kg.s  "mole per kilogram second"
* $ucum#mol/d  "mole per day"
* $ucum#ng/[IU]  "nanogram per international unit"
* $ucum#nkat/L  "nanokatal per liter"
* $ucum#nmol/kg  "nanomole per kilogram"
* $ucum#nmol/m3  "nanomole per cubic meter"
* $ucum#pmol/kg  "picomole per kilogram"
* $ucum#pmol/m3  "picomole per cubic meter"
* $ucum#pU  "pico enzyme unit"
* $ucum#U/kg  "enzyme unit per kilogram"
* $ucum#ukat/d  "microkatal per day"
* $ucum#ukat/kg  "microkatal per kilogram"
* $ucum#ukat/L  "microkatal per liter"
* $ucum#ukat/s  "microkatal per second"
* $ucum#um2  "square micrometer"
* $ucum#umol/kg.s  "micromole per kilogram second"
* $ucum#umol/m3  "micromole per cubic meter"